### PR TITLE
Danielpatton/sc 8798/refactor react payment example to be more

### PR DESCRIPTION
**Pull request by dpatton1992**
This PR creates the custom Tilled.js hook, `useTilled` that` takes the following params:
- `account_id`: the Tilled merchant account id. Ex: `acct_XXXX`
- `public_key`: publishable Tilled API key. Ex: `pk_XXXX`
- `paymentTypeObj`: an object with the payment method `type` and and object describing the `fields` to be injected. Ex:
```
creditCard: {
    type: 'card',
    fields: {
      cardNumber: "#card-number-element",
      cardExpiry: "#card-expiration-element",
      cardCvv: "#card-cvv-element",
    }
  }
```
- `fieldOptions`: The Tilled.js form [options object](https://docs.tilled.com/tilledjs/#formcreatefieldformfieldtype-options-formfield). Ex: 
```
const fieldOptions = {
    styles: {
      base: {
        fontFamily:
          '-apple-system, "system-ui", "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif',
        color: "#304166",
        fontWeight: "400",
        fontSize: "16px",
      },
      invalid: {
        ":hover": {
          textDecoration: "underline dotted red",
        },
        color: "#777777",
      },
      valid: {
        color: "#32CD32",
      },
    },
  };
```

This hook can be called from inside the component containing the Tilled.js fields and uses the `useScript` hook to insert the Tilled.js script into the DOM. When the component it's called from mounts, it waits until the script is ready and then does the following:
- Creates a new Tilled instance
- Awaits a new `form` instance
- loops through and inject the paymentTypeObj.fields
- Sets the placeholder for cardExpiry
- Updates the card brand if the DOM contains and element with the `#card-brand-icon` selector
- builds the form

Once the component unmounts, it checks to see if a form exists and runs the [teardown method](https://docs.tilled.com/tilledjs/#formteardownhandler-promiseboolean--void).
This hook was created to make this example more reactive and to make it easier for Tilled partners to get up and running with Tilled.

### CODE REVIEW

**Comment by dpatton1992** [comment]
In strict mode, teardown method should run twice. When tabbing to bank transfer and back to card it runs twice for the bank transfer fields and twice again for the card fields.
Screen Shot 2022-12-07 at 11 39 35 AM

Multiple dom element still present as in this [issue](https://github.com/gettilled/tilled-example-monorepo/issues/10)

**Comment by dpatton1992** [comment]
Credit card works in strict mode, but additional inputs are still being inserted when tabbing between the two types.

**Review by bdeklerk0 — DISMISSED** [review]

**Review by bdeklerk0 — APPROVED** [review]

**Comment by imtmh** [comment]
I am still seeing the issue of duplicate fields getting injected in iframe.

**Comment by dpatton1992** [comment]
> I am still seeing the issue of duplicate fields getting injected in iframe.

Sorry, I am unable to recreate the issue after the changes to useTilled.js in [PR #79](https://github.com/gettilled/tilled-example-monorepo/pull/79/files#top). Please open an issue with a screen recording showing the issue using the example or contact integrations@tilled.com to set up a meeting to debug your integration.

**Pull request merged**
